### PR TITLE
Internalization of anonymous external data

### LINKED ISSUE #51: Internalization of external sources that don't define `Class` or `MimeType` equivalents
What's the proper way of going about using the internalization mechanisms, in particular object factory resolution, for data that comes from third party apis that don't provide any explicit declaration of type like `Class` or `MimeType` on nested objects?  This seems like a common case when working with data from non NTI sources.   For example an API that returns a list of orders structured something like this:

```json
{
    "orders": [
           {"foo": "bar"},
           {"foo": "baz"}
    ]
}
```

There may not be properties that explicitly identify the nested objects in the `orders` field as `Order` objects, however I as the programmer know that the contract of the API defines the contents of orders are `Order` objects.  Obviously this is a recursive problem.  Each `Order` may have a `caption` field that we want to resolve to a `Caption` object.

Is the solution to recursively preprocess the raw json dict to add `MimeType` to any nested objects? That feels nasty.  It seems like there could be a solution where the nested factory lookups could take in to account the containing object being parsed as well as the field being parsed.  i.e. Use this factory if parsing this field on this type of object.  

I think I could almost make that work using the deprecated functionality in [Issue 29](https://github.com/NextThought/nti.externalization/issues/29) but seeing as how that is going away that obviously wouldn't be a good approach.  This does seem like a general problem that I've encountered working with a number of external sources.  What are the thoughts on how to handle something like this.

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #51 

Needs documentation and some cleanups yet.

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks. I realize I need a more complete change note now that the implementation is more settled, and I would still appreciate a second review from @jzuech3 given the recent experiences implementing this “manually”. If it’s not a significant improvement in many situations we may be back to the drawing board.

**Comment by jamadden** [comment]
In adding 6c878f6fac3780f0c18b24c807830ac66c4cf3fd, the 'addresses' field was originally just a `Dict` with a value type of `Object(IAddress)`. We couldn't internalize that correctly. The output was something like `{'addresses': {'work': {'MimeType': ...}}}`, but `addresses` itself wasn't a modelled object and had no factory. Thus the introduction of the `IAddresses` object to contain that layer. 

This could let that be simplified again.

**Comment by cutz** [comment]
@jamadden @jzuech3  when do we expect we can cut a version with this new functionality?

**Comment by jamadden** [comment]
I want to merge #71 (which frankly is *probably* just about as done as it's going to get; I have some PRs working in other repos to better improve the things we can link to, and anyway, most of the further work will probably be in .rst files, not docstrings, so it wouldn't affect a released project much). I'd still appreciate some feedback on this issue too, so of course if the feedback is negative there may be some more work to do.

**Comment by jzuech3** [comment]
Sure, I can take a look here in a few.

**Comment by jamadden** [comment]
I've gone ahead and released 1.0a3 to PyPI. I'm still interested in any feedback, but that might be easier to come by if it's released 😄 I'm not building the full matrix of binaries, so releases are relatively cheap.

**Comment by jamadden** [comment]
Thanks!

**Pull request merged**
